//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int bookID { get; set; }
        public string bookTitle { get; set; }
        public string seriesTitle { get; set; }
        public Nullable<System.DateTime> publishDate { get; set; }
        public string genre { get; set; }
        public string bookDescription { get; set; }
        public string image { get; set; }
    }
}
